### PR TITLE
Add icons in vehicles

### PR DESCRIPTION
**Pull request by ElkinMoreno01226**

### CODE REVIEW

**Comment by diferpaho** [comment]
It is modifying 4 files when the vehicles.html should be modified, also add the edit button with its icon as in the example

**Comment by ElkinMoreno01226** [comment]
new commit whit only 1 file modified, please check it, tank you.

**Comment by diferpaho** [comment]
> new commit whit only 1 file modified, please check it, tank you.

Above in "modified files" it seems that it modifies 4 files, please upload a commit where you do not modify the other 3.

**Comment by ElkinMoreno01226** [comment]
Hi, I send you a commit whit only 1 file modified, i dont know how reverse the first commit, please if you can  tell me how i do it i apreciate to much.

**Comment by diferpaho** [comment]
Pull request closed because changes were made to the location of the templates and the task must be performed differently, equally good job!

**Pull request closed without merging**
