### PR TITLE
Release/front end

### PR DESCRIPTION
**Pull request by diferpaho**
New version of the front end, please upload a production.

### CODE REVIEW

**Comment by danialeresbar** [comment]
Please, resolve the conflicts!

**Comment by diferpaho** [comment]
> Please, resolve the conflicts!

Sorry, conflicts fixed and pull request ready.

**Review by danialeresbar — APPROVED** [review]
A new app has been created and some harvests app models were moved to the new app. Please make the respective transfer of templates and statics there

Thanks

**Comment by diferpaho** [comment]
> A new app has been created and some harvests app models were moved to the new app. Please make the respective transfer of templates and statics there

So far we only have templates for vehicles, place of origin and people, in the reports app there are also templates for them, but I don't see that any of them moved, so it can be integrated and go into production. Likewise, if I see something out of place, I will correct it in the following commits.

**Comment by danialeresbar** [comment]
I will integrate all the changes coming from now on to this branch without review since it is your task that part. You don't seem to have understood the comment above and there seems to be a rush, so I'll integrate it.

I will only check if sensitive files are touched, and I will block the PR.

**Pull request merged**
