### PR TITLE
Change the words in the buttons of /origin by icons

### PR DESCRIPTION
**Pull request by juan5d**
Confirm is changed correct #50

### CODE REVIEW

**Comment by diferpaho** [comment]
Add the icons for the search, add and add button to edit as in the example.

**Comment by juan5d** [comment]
Confirm is changed correct #50

**Comment by diferpaho** [comment]
The file you modify is harvests `/templates/origin.html ` but now that file has been moved to sources `/templates/origin.html`, please update your `release/front-end` branch and add the icons for the file that was moved, also add the edit button with its respective icon.

**Comment by diferpaho** [comment]
closed by new pull request with the same task

**Pull request closed without merging**
